### ISSUE TITLE
Setting to adjust tooltip duration

### ISSUE THREAD

**Issue by Myrthian** [Argent77/A7-HiddenGameplayOptions#1]
I might have missed the setting, but in EE the tooltips for examining item on the map are persisting for ~7 seconds, but in the normal version ~4 seconds.

I'm a fast reader, and quickly examining several objects leads to having several tooltips hanging around and breaking immersion.

**Comment by Argent77** [comment]
Can you elaborate further? Which tooltips do you mean?

**Comment by Myrthian** [comment]
Urgh, my bad: I took a screenshot, but thought the description would be enough, but even that was imprecise.

I'm talking about the tooltips or rather description texts which you will see by examining certain POIs in any location: you can stack the on the screen if you quickly examine several, which really breaks the immersion.

https://i.imgur.com/4FIoSQY.png

**Comment by Argent77** [comment]
Ah, the floating text. Their duration appears to be calculated by the game engine based on text length. I fear that's hardcoded too. The only way (I know of) to control display length of floating text is via special script actions which reduce display time based on the associated sound clips. This is only really useful for cutscene content though, where dialog lines have to be timed correctly. In any case there is no global flag to control display duration of floating text.
