### ISSUE TITLE
[FAQ / Documentation] Suggestion to explain the following

### ISSUE THREAD

**Issue by rubyFeedback** [Argent77/A7-HiddenGameplayOptions#12]
Some of the features sound great, so perhaps you could add some clarification,
ideally in a FAQ or README or separate entry unde doc/ or something like that,
or a link to the github wiki - all works fine.

1) Are there known incompatibilities to other mods?

2) Can this be installed lateron? For instance I batch-installed about 40 mods;
I don't want to re-install them. Can I add hidden gameplay options? I am
fine starting a new game, I would just like to know in advance whether existing
mods installations may break as a result.

Hmm. I have a few more questions probably related to some of the options,
e. g. does the old lua console work or not after installing this mod, and some
more like that, but I think I first have to test it.

**Comment by Argent77** [comment]
> Some of the features sound great, so perhaps you could add some clarification, ideally in a FAQ or README or separate entry unde doc/ or something like that, or a link to the github wiki - all works fine.
> 
>     1. Are there known incompatibilities to other mods?
> 
>     2. Can this be installed lateron? For instance I batch-installed about 40 mods;
>        I don't want to re-install them. Can I add hidden gameplay options? I am
>        fine starting a new game, I would just like to know in advance whether existing
>        mods installations may break as a result.

That's already included in the readme:
https://github.com/Argent77/A7-HiddenGameplayOptions/blob/978f0a6eb1ca486d586450b32ec9cc139b56b278/HiddenGameplayOptions/readme/readme.txt#L40-L57
<br/>
> Hmm. I have a few more questions probably related to some of the options, e. g. does the old lua console work or not after installing this mod, and some more like that, but I think I first have to test it.

The game console is only modified by the "Improved Cheat Menu" subcomponent. It improves only the convenience ui section in the upper portion of the screen though. The actual lua prompt is not modified.
