### ISSUE TITLE
UI scaling setting for the toolbar

### ISSUE THREAD

**Issue by Myrthian** [Argent77/A7-HiddenGameplayOptions#2]
Is there a possibility to have a scaling setting just for the toolbar?

As far as I can tell I can either enable or disable the UI scaling, but I do want to have it enabled as reading is much more pleasant with a bigger font, but then the size of the toolbar + party frames is just out-of-place with their immense size.

**Comment by Argent77** [comment]
Unfortunately there is no such setting provided by the game engine. You could try one of the [GUI mods](https://forums.beamdog.com/discussion/77445/list-of-ui-mods) instead.

**Comment by Myrthian** [comment]
Sad, but I can live with the workaround: disabling UI scale in Baldur.lua + scaling the font size up until reading text is enjoyable.
