### ISSUE TITLE
How to reset UI?

### ISSUE THREAD

**Issue by notNSANE** [Argent77/A7-HiddenGameplayOptions#4]
I changed a couple things but overdid it, and the changes seem permantent. How to reset the UI?

**Comment by Argent77** [comment]
To reset all game options to their defaults go into the `Documents/Baldur's Gate - Enhanced Edition` (for BGEE) and delete or rename the `Baldur.lua` file.

If you had enabled the option "Enable UI Edit Mode" and moved UI elements around in the game you might also have to delete the `UI.MENU` file from the game's `override` folder. However, then you'll also have to reinstall this mod afterwards.
