### ISSUE TITLE
Compatibility with Infinity UI

### ISSUE THREAD

**Issue by jcvignoli** [Argent77/A7-HiddenGameplayOptions#8]
Hi,

I noticed that the mod is mostly compatible with Dragonspear UI, but barely with Infinity UI.

Is there a particular reason for that ? Dragonspear is not developped anymore, while Infinity is very actively developped.

Thanks!

**Comment by Argent77** [comment]
The reason for this was *because* Infinity UI is still being actively developed. Each new version carried the risk of compatibility issues due to internal code changes.

It looks like development has slowed down recently, however. I'll see if I can add compatibility for Infinity UI.

**Comment by jcvignoli** [comment]
I understand, indeed, it pretty active :)
Looking forward for a compatiblity!

**Comment by Argent77** [comment]
Infinity UI++ support has been added: 6c2a91a1ebbe224f9e7a7783e08ab361c18357a4

**Comment by jcvignoli** [comment]
I confirm it works on my side, thanks @Argent77 !
