### ISSUE TITLE
Compatibility with dragonUI++

### ISSUE THREAD

**Issue by jcvignoli** [Argent77/A7-HiddenGameplayOptions#9]
Since the mod is not yet compatible with infinityUI, I installed it with dragonUI.
But HiddenGame installs with warnings with the latter:

>WARNING: CLABMA01.2DA] Unexpected number of columns in row 3 (expected: 51, found: 41)
> Copying and patching 1 file ...
> [./override/CLABFI01.2DA] loaded, 3995 bytes
> 
> WARNING: [CLABFI01.2DA] Unexpected number of columns in row 3 (expected: 51, found: 41)
> 
> WARNING: [CLABFI01.2DA] Unexpected number of columns in row 4 (expected: 51, found: 41)
> 
> WARNING: [CLABFI01.2DA] Unexpected number of columns in row 5 (expected: 51, found: 41)
> 
> WARNING: [CLABFI01.2DA] Unexpected number of columns in row 6 (expected: 51, found: 41)
> 
> WARNING: [CLABFI01.2DA] Unexpected number of columns in row 7 (expected: 51, found: 41)
> 
> WARNING: [CLABFI01.2DA] Unexpected number of columns in row 8 (expected: 51, found: 41)
> Copying and patching 1 file ...
> [./override/CLABPR01.2DA] loaded, 4038 bytes
> 
> WARNING: [CLABPR01.2DA] Unexpected number of columns in row 3 (expected: 51, found: 41)
> 
> WARNING: [CLABPR01.2DA] Unexpected number of columns in row 4 (expected: 51, found: 41)
> 
> WARNING: [CLABPR01.2DA] Unexpected number of columns in row 5 (expected: 51, found: 41)
> 
> WARNING: [CLABPR01.2DA] Unexpected number of columns in row 6 (expected: 51, found: 41)
> 
> WARNING: [CLABPR01.2DA] Unexpected number of columns in row 7 (expected: 51, found: 41)
> 
> WARNING: [CLABPR01.2DA] Unexpected number of columns in row 8 (expected: 51, found: 41)
> Copying and patching 1 file ...

I attach the debug file.
[setup-hiddengameplayoptions.zip](https://github.com/Argent77/A7-HiddenGameplayOptions/files/13364407/setup-hiddengameplayoptions.zip)

**Comment by Argent77** [comment]
This warning is triggered if the respective files contain an unexpected number of columns. This is not related to the Dragonspear UI++ but rather caused by some other mod that incorrectly modified or expanded kit ability tables.

This is only feedback for the user though and does not negatively affect the mod installation.
